### ISSUE TITLE
Output versions of geosupport and input data

### ISSUE THREAD

**Issue by mgraber** [NYCPlanning/db-gru-qaqc#14]
Create a versions.txt output for each check. Should contain versions associated with geosupport, and (where applicable) dcp_developments, doitt_buildingfootprints version, dcp_addresspoints, dcp_atomicpolygons.

**Comment by SPTKL** [comment]
docker-geosupport has the following environmental variables: 
```
RELEASE=20a
MAJOR=20
MINOR=1
PATCH=2
```
PATCH indicates UPAD version, call it UPAD might be easier for GRU
https://github.com/NYCPlanning/docker-geosupport
